name: Build
description: "Runs Quilt’s build command on your workspace"
inputs:
  arguments:
    description: "Additional arguments to pass to Quilt’s build command"
    required: false
    default: ""
  command:
    description: "The command to run to start Quilt’s build"
    required: false
    default: "node_modules/.bin/quilt build"
  cache-key:
    description: "A key to include in caching build outputs"
    required: false
    default: "v1"
runs:
  using: "composite"
  steps:
    - uses: actions/cache@v2
      id: typescript-cache
      name: Restore TypeScript cache
      with:
        path: |
          **/build/typescript/
          **/*.tsbuildinfo
        key: ${{ runner.os }}-build-typescript-${{ inputs.cache-key }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-build-typescript-${{ inputs.cache-key }}-

    - name: Build
      run: ${{ inputs.command }} ${{ inputs.arguments }}
      shell: bash
