name: Build
description: "Runs Quilt’s build command on your workspace"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v1
      name: Checkout

    - uses: actions/setup-node@v2
      name: Setup node.js and yarn
      with:
        node-version: 16.2.0
        cache: yarn

    - name: Yarn install
      run: yarn install --immutable
      shell: bash

    - uses: actions/cache@v2
      id: typescript-cache
      name: Restore TypeScript cache
      with:
        path: |
          **/build/typescript/
          **/*.tsbuildinfo
        key: ${{ runner.os }}-build-typescript-v1-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-build-typescript-v1-

    - name: Build
      run: yarn build
      shell: bash
